# Generated by Django 5.2.6 on 2026-03-19 14:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0004_alter_inventory_options_alter_tax_options_and_more'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='purchaseitem',
            constraint=models.UniqueConstraint(fields=('voucher', 'product', 'lot_number'), name='unique_voucher_product_lot'),
        ),
    ]
