# Generated by Django 5.2.6 on 2026-03-20 09:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0005_purchaseitem_unique_voucher_product_lot'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='tax',
            options={'ordering': ['order']},
        ),
        migrations.RemoveField(
            model_name='product',
            name='tax',
        ),
        migrations.AddField(
            model_name='product',
            name='taxes',
            field=models.ManyToManyField(to='inventory.tax'),
        ),
        migrations.AddField(
            model_name='tax',
            name='order',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='purchasevoucher',
            name='supplier',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='inventory.supplier'),
        ),
    ]
