# Generated by Django 5.2.6 on 2026-03-20 12:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0006_alter_tax_options_remove_product_tax_product_taxes_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tax',
            name='is_compound',
            field=models.BooleanField(default=False, help_text='If True, calculated on top of base amount + single taxes'),
        ),
        migrations.AlterField(
            model_name='tax',
            name='percentage',
            field=models.DecimalField(decimal_places=2, help_text='Enter as percentage, e.g., 5.00', max_digits=5),
        ),
    ]
